/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef SIHTTP_BAKE_CONFIG_H
#define SIHTTP_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <sireflect.h>
#include <sijson.h>

/* Convenience macro for exporting symbols */
#ifndef sihttp_STATIC
#if defined(sihttp_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define SIHTTP_API __declspec(dllexport)
#elif defined(sihttp_EXPORTS)
  #define SIHTTP_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define SIHTTP_API __declspec(dllimport)
#else
  #define SIHTTP_API
#endif
#else
  #define SIHTTP_API
#endif

#endif

